name: Subir assets a public_html

on:
  push:
    branches:
      - main  # O tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    # Subir carpeta build/
    - name: Subir carpeta build/
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USER }}
        password: ${{ secrets.HOSTINGER_PASS }}
        local-dir: ./public/build/
        server-dir: ./build/

    # Subir carpeta img/
    - name: Subir carpeta img/
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USER }}
        password: ${{ secrets.HOSTINGER_PASS }}
        local-dir: ./public/img/
        server-dir: ./img/

    # Subir carpeta videos/
    - name: Subir carpeta videos/
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USER }}
        password: ${{ secrets.HOSTINGER_PASS }}
        local-dir: ./public/videos/
        server-dir: ./videos/